services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  backend:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    ports:
      - 15001:15001
    command: "npm start"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/home/node/app
    ports:
      - 15002:15002
    command: "npm run start"
    depends_on:
      postgres:
        condition: service_healthy

  admin:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./admin:/home/node/app
    ports:
      - 15003:15003
    command: "npm run start"
    depends_on:
      postgres:
        condition: service_healthy