services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always

  backend:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    ports:
      - 15001:15001
    command: "npm start"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/home/node/app
    ports:
      - 15002:15002
    command: "npm run start"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  admin:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./admin:/home/node/app
    ports:
      - 15003:15003
    command: "npm run start"
    depends_on:
      postgres:
        condition: service_healthy

  docker_bot:
    build: ./bot
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  # backup:
  #   build: ./db_backup
  #   volumes:
  #     - ./db_backup/backups/:/var/lib/postgresql/
  #   command: "crond -f -d 8"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
      
  file_server:
    build: ./challenges/
    volumes:
      - ./challenges:/project
    ports:
      - 15004:8003
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  level_11:
    build: ./challenges/
    ports:
      - 16000:8003
    volumes:
      - ./challenges/level_11/build:/project
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  